rules = "special_indexes"
options = []

[[groups]]
layout = "layout_a"
variant = "extra"

[[groups]]
layout = "layout_b"
variant = ""

[[groups]]
layout = "layout_c"
variant = ""

[[groups]]
layout = "layout_d"
variant = "extra"
