keycodes = "evdev+aliases(qwerty)"
types = "complete"
compat = "complete+caps(caps_lock):2+misc(assign_shift_left_action):2+level5(level5_lock):2"
symbols = "pc+gb+de(neo):2+inet(evdev)"
geometry = "pc(pc104)"
