use super::*;

pub(super) const LONGEST: usize = 23;

#[derive(Copy, Clone, Eq, PartialEq, Debug)]
pub(crate) enum Meaning {
    __Unknown,
    Accel,
    Accelerate,
    Action,
    ActionMessage,
    Actions,
    Affect,
    Alias,
    All,
    Allowexplicit,
    Allownone,
    AlphanumericKeys,
    Alternate,
    AlternateGroup,
    Any,
    Augment,
    Both,
    Button,
    Clampgroups,
    ClearLocks,
    Clearmodifiers,
    Clearmods,
    Control,
    Controls,
    Count,
    Ctrls,
    Data,
    Default,
    Defaultbutton,
    Dev,
    DevBtn,
    DevButton,
    Device,
    DeviceBtn,
    DeviceButton,
    DeviceVal,
    DeviceValuator,
    DevVal,
    DevValuator,
    Dfltbtn,
    Driveskbd,
    Driveskeyboard,
    False,
    FunctionKeys,
    GenerateKeyEvent,
    GenKeyEvent,
    Group,
    Groupname,
    Groups,
    Groupsclamp,
    Groupsredirect,
    Groupswrap,
    Hidden,
    Include,
    Increment,
    Index,
    Indicator,
    Indicatordriveskbd,
    Indicatordriveskeyboard,
    Interpret,
    ISOLock,
    Kc,
    Key,
    Keycode,
    KeypadKeys,
    Keys,
    LatchGroup,
    LatchMods,
    LatchToLock,
    Leddriveskbd,
    Leddriveskeyboard,
    LevelName,
    Lock,
    LockControls,
    LockDevBtn,
    LockDevButton,
    LockDeviceBtn,
    LockDeviceButton,
    LockGroup,
    Locking,
    LockMods,
    LockPointerBtn,
    LockPointerButton,
    LockPtrBtn,
    LockPtrButton,
    Locks,
    Logo,
    Map,
    Maximum,
    Message,
    MessageAction,
    Mod1,
    Mod2,
    Mod3,
    Mod4,
    Mod5,
    ModifierKeys,
    ModifierMap,
    Modifiers,
    ModMap,
    Modmap,
    Modmapmods,
    Mods,
    MovePointer,
    MovePtr,
    Name,
    Neither,
    No,
    NoAction,
    None,
    Nosymbol,
    Off,
    On,
    Outline,
    Overlay,
    Override,
    Partial,
    Permanentradiogroup,
    PointerButton,
    Preserve,
    Private,
    PtrBtn,
    Radiogroup,
    Redirect,
    Redirectgroups,
    RedirectKey,
    Repeat,
    Repeating,
    Repeats,
    Replace,
    Report,
    Row,
    Same,
    SameServer,
    Screen,
    Section,
    SetControls,
    SetGroup,
    SetMods,
    SetPointerDefault,
    SetPtrDflt,
    Shape,
    Shift,
    Solid,
    SwitchScreen,
    Symbols,
    Terminate,
    TerminateServer,
    Text,
    True,
    Type,
    Unlock,
    Usemodmap,
    Usemodmapmods,
    Value,
    Virtual,
    Virtualmod,
    Virtualmodifier,
    VirtualModifiers,
    Virtualmodifiers,
    Virtualmods,
    Vmods,
    Voidsymbol,
    Whichgroupstate,
    Whichmodifierstate,
    Whichmodstate,
    Wrapgroups,
    X,
    XkbCompat,
    XkbCompatibility,
    XkbCompatibilityMap,
    XkbCompatMap,
    XkbGeometry,
    XkbKeycodes,
    XkbKeymap,
    XkbLayout,
    XkbSemantics,
    XkbSymbols,
    XkbTypes,
    Y,
    Yes,
}

impl Meaning {
    pub fn name(self) -> &'static str {
        match self {
            Self::__Unknown => "__Unknown",
            Self::Accel => "accel",
            Self::Accelerate => "accelerate",
            Self::Action => "action",
            Self::ActionMessage => "ActionMessage",
            Self::Actions => "actions",
            Self::Affect => "affect",
            Self::Alias => "alias",
            Self::All => "all",
            Self::Allowexplicit => "allowexplicit",
            Self::Allownone => "allownone",
            Self::AlphanumericKeys => "alphanumeric_keys",
            Self::Alternate => "alternate",
            Self::AlternateGroup => "alternate_group",
            Self::Any => "any",
            Self::Augment => "augment",
            Self::Both => "both",
            Self::Button => "button",
            Self::Clampgroups => "clampgroups",
            Self::ClearLocks => "clearLocks",
            Self::Clearmodifiers => "clearmodifiers",
            Self::Clearmods => "clearmods",
            Self::Control => "Control",
            Self::Controls => "controls",
            Self::Count => "count",
            Self::Ctrls => "ctrls",
            Self::Data => "data",
            Self::Default => "default",
            Self::Defaultbutton => "defaultbutton",
            Self::Dev => "dev",
            Self::DevBtn => "DevBtn",
            Self::DevButton => "DevButton",
            Self::Device => "device",
            Self::DeviceBtn => "DeviceBtn",
            Self::DeviceButton => "DeviceButton",
            Self::DeviceVal => "DeviceVal",
            Self::DeviceValuator => "DeviceValuator",
            Self::DevVal => "DevVal",
            Self::DevValuator => "DevValuator",
            Self::Dfltbtn => "dfltbtn",
            Self::Driveskbd => "driveskbd",
            Self::Driveskeyboard => "driveskeyboard",
            Self::False => "false",
            Self::FunctionKeys => "function_keys",
            Self::GenerateKeyEvent => "generateKeyEvent",
            Self::GenKeyEvent => "genKeyEvent",
            Self::Group => "group",
            Self::Groupname => "groupname",
            Self::Groups => "groups",
            Self::Groupsclamp => "groupsclamp",
            Self::Groupsredirect => "groupsredirect",
            Self::Groupswrap => "groupswrap",
            Self::Hidden => "hidden",
            Self::Include => "include",
            Self::Increment => "increment",
            Self::Index => "index",
            Self::Indicator => "indicator",
            Self::Indicatordriveskbd => "indicatordriveskbd",
            Self::Indicatordriveskeyboard => "indicatordriveskeyboard",
            Self::Interpret => "interpret",
            Self::ISOLock => "ISOLock",
            Self::Kc => "kc",
            Self::Key => "key",
            Self::Keycode => "keycode",
            Self::KeypadKeys => "keypad_keys",
            Self::Keys => "keys",
            Self::LatchGroup => "LatchGroup",
            Self::LatchMods => "LatchMods",
            Self::LatchToLock => "latchToLock",
            Self::Leddriveskbd => "leddriveskbd",
            Self::Leddriveskeyboard => "leddriveskeyboard",
            Self::LevelName => "level_name",
            Self::Lock => "Lock",
            Self::LockControls => "LockControls",
            Self::LockDevBtn => "LockDevBtn",
            Self::LockDevButton => "LockDevButton",
            Self::LockDeviceBtn => "LockDeviceBtn",
            Self::LockDeviceButton => "LockDeviceButton",
            Self::LockGroup => "LockGroup",
            Self::Locking => "locking",
            Self::LockMods => "LockMods",
            Self::LockPointerBtn => "LockPointerBtn",
            Self::LockPointerButton => "LockPointerButton",
            Self::LockPtrBtn => "LockPtrBtn",
            Self::LockPtrButton => "LockPtrButton",
            Self::Locks => "locks",
            Self::Logo => "logo",
            Self::Map => "map",
            Self::Maximum => "maximum",
            Self::Message => "Message",
            Self::MessageAction => "MessageAction",
            Self::Mod1 => "Mod1",
            Self::Mod2 => "Mod2",
            Self::Mod3 => "Mod3",
            Self::Mod4 => "Mod4",
            Self::Mod5 => "Mod5",
            Self::ModifierKeys => "modifier_keys",
            Self::ModifierMap => "modifier_map",
            Self::Modifiers => "modifiers",
            Self::ModMap => "mod_map",
            Self::Modmap => "modmap",
            Self::Modmapmods => "modmapmods",
            Self::Mods => "mods",
            Self::MovePointer => "MovePointer",
            Self::MovePtr => "MovePtr",
            Self::Name => "name",
            Self::Neither => "neither",
            Self::No => "no",
            Self::NoAction => "NoAction",
            Self::None => "none",
            Self::Nosymbol => "nosymbol",
            Self::Off => "off",
            Self::On => "on",
            Self::Outline => "outline",
            Self::Overlay => "overlay",
            Self::Override => "override",
            Self::Partial => "partial",
            Self::Permanentradiogroup => "permanentradiogroup",
            Self::PointerButton => "PointerButton",
            Self::Preserve => "preserve",
            Self::Private => "Private",
            Self::PtrBtn => "PtrBtn",
            Self::Radiogroup => "radiogroup",
            Self::Redirect => "Redirect",
            Self::Redirectgroups => "redirectgroups",
            Self::RedirectKey => "RedirectKey",
            Self::Repeat => "repeat",
            Self::Repeating => "repeating",
            Self::Repeats => "repeats",
            Self::Replace => "replace",
            Self::Report => "report",
            Self::Row => "row",
            Self::Same => "same",
            Self::SameServer => "sameServer",
            Self::Screen => "screen",
            Self::Section => "section",
            Self::SetControls => "SetControls",
            Self::SetGroup => "SetGroup",
            Self::SetMods => "SetMods",
            Self::SetPointerDefault => "SetPointerDefault",
            Self::SetPtrDflt => "SetPtrDflt",
            Self::Shape => "shape",
            Self::Shift => "Shift",
            Self::Solid => "solid",
            Self::SwitchScreen => "SwitchScreen",
            Self::Symbols => "symbols",
            Self::Terminate => "Terminate",
            Self::TerminateServer => "TerminateServer",
            Self::Text => "text",
            Self::True => "true",
            Self::Type => "type",
            Self::Unlock => "unlock",
            Self::Usemodmap => "usemodmap",
            Self::Usemodmapmods => "usemodmapmods",
            Self::Value => "value",
            Self::Virtual => "virtual",
            Self::Virtualmod => "virtualmod",
            Self::Virtualmodifier => "virtualmodifier",
            Self::VirtualModifiers => "virtual_modifiers",
            Self::Virtualmodifiers => "virtualmodifiers",
            Self::Virtualmods => "virtualmods",
            Self::Vmods => "vmods",
            Self::Voidsymbol => "voidsymbol",
            Self::Whichgroupstate => "whichgroupstate",
            Self::Whichmodifierstate => "whichmodifierstate",
            Self::Whichmodstate => "whichmodstate",
            Self::Wrapgroups => "wrapgroups",
            Self::X => "x",
            Self::XkbCompat => "xkb_compat",
            Self::XkbCompatibility => "xkb_compatibility",
            Self::XkbCompatibilityMap => "xkb_compatibility_map",
            Self::XkbCompatMap => "xkb_compat_map",
            Self::XkbGeometry => "xkb_geometry",
            Self::XkbKeycodes => "xkb_keycodes",
            Self::XkbKeymap => "xkb_keymap",
            Self::XkbLayout => "xkb_layout",
            Self::XkbSemantics => "xkb_semantics",
            Self::XkbSymbols => "xkb_symbols",
            Self::XkbTypes => "xkb_types",
            Self::Y => "y",
            Self::Yes => "yes",
        }
    }

    pub(super) fn lowercase(self) -> &'static str {
        match self {
            Self::__Unknown => "__Unknown",
            Self::Accel => "accel",
            Self::Accelerate => "accelerate",
            Self::Action => "action",
            Self::ActionMessage => "actionmessage",
            Self::Actions => "actions",
            Self::Affect => "affect",
            Self::Alias => "alias",
            Self::All => "all",
            Self::Allowexplicit => "allowexplicit",
            Self::Allownone => "allownone",
            Self::AlphanumericKeys => "alphanumeric_keys",
            Self::Alternate => "alternate",
            Self::AlternateGroup => "alternate_group",
            Self::Any => "any",
            Self::Augment => "augment",
            Self::Both => "both",
            Self::Button => "button",
            Self::Clampgroups => "clampgroups",
            Self::ClearLocks => "clearlocks",
            Self::Clearmodifiers => "clearmodifiers",
            Self::Clearmods => "clearmods",
            Self::Control => "control",
            Self::Controls => "controls",
            Self::Count => "count",
            Self::Ctrls => "ctrls",
            Self::Data => "data",
            Self::Default => "default",
            Self::Defaultbutton => "defaultbutton",
            Self::Dev => "dev",
            Self::DevBtn => "devbtn",
            Self::DevButton => "devbutton",
            Self::Device => "device",
            Self::DeviceBtn => "devicebtn",
            Self::DeviceButton => "devicebutton",
            Self::DeviceVal => "deviceval",
            Self::DeviceValuator => "devicevaluator",
            Self::DevVal => "devval",
            Self::DevValuator => "devvaluator",
            Self::Dfltbtn => "dfltbtn",
            Self::Driveskbd => "driveskbd",
            Self::Driveskeyboard => "driveskeyboard",
            Self::False => "false",
            Self::FunctionKeys => "function_keys",
            Self::GenerateKeyEvent => "generatekeyevent",
            Self::GenKeyEvent => "genkeyevent",
            Self::Group => "group",
            Self::Groupname => "groupname",
            Self::Groups => "groups",
            Self::Groupsclamp => "groupsclamp",
            Self::Groupsredirect => "groupsredirect",
            Self::Groupswrap => "groupswrap",
            Self::Hidden => "hidden",
            Self::Include => "include",
            Self::Increment => "increment",
            Self::Index => "index",
            Self::Indicator => "indicator",
            Self::Indicatordriveskbd => "indicatordriveskbd",
            Self::Indicatordriveskeyboard => "indicatordriveskeyboard",
            Self::Interpret => "interpret",
            Self::ISOLock => "isolock",
            Self::Kc => "kc",
            Self::Key => "key",
            Self::Keycode => "keycode",
            Self::KeypadKeys => "keypad_keys",
            Self::Keys => "keys",
            Self::LatchGroup => "latchgroup",
            Self::LatchMods => "latchmods",
            Self::LatchToLock => "latchtolock",
            Self::Leddriveskbd => "leddriveskbd",
            Self::Leddriveskeyboard => "leddriveskeyboard",
            Self::LevelName => "level_name",
            Self::Lock => "lock",
            Self::LockControls => "lockcontrols",
            Self::LockDevBtn => "lockdevbtn",
            Self::LockDevButton => "lockdevbutton",
            Self::LockDeviceBtn => "lockdevicebtn",
            Self::LockDeviceButton => "lockdevicebutton",
            Self::LockGroup => "lockgroup",
            Self::Locking => "locking",
            Self::LockMods => "lockmods",
            Self::LockPointerBtn => "lockpointerbtn",
            Self::LockPointerButton => "lockpointerbutton",
            Self::LockPtrBtn => "lockptrbtn",
            Self::LockPtrButton => "lockptrbutton",
            Self::Locks => "locks",
            Self::Logo => "logo",
            Self::Map => "map",
            Self::Maximum => "maximum",
            Self::Message => "message",
            Self::MessageAction => "messageaction",
            Self::Mod1 => "mod1",
            Self::Mod2 => "mod2",
            Self::Mod3 => "mod3",
            Self::Mod4 => "mod4",
            Self::Mod5 => "mod5",
            Self::ModifierKeys => "modifier_keys",
            Self::ModifierMap => "modifier_map",
            Self::Modifiers => "modifiers",
            Self::ModMap => "mod_map",
            Self::Modmap => "modmap",
            Self::Modmapmods => "modmapmods",
            Self::Mods => "mods",
            Self::MovePointer => "movepointer",
            Self::MovePtr => "moveptr",
            Self::Name => "name",
            Self::Neither => "neither",
            Self::No => "no",
            Self::NoAction => "noaction",
            Self::None => "none",
            Self::Nosymbol => "nosymbol",
            Self::Off => "off",
            Self::On => "on",
            Self::Outline => "outline",
            Self::Overlay => "overlay",
            Self::Override => "override",
            Self::Partial => "partial",
            Self::Permanentradiogroup => "permanentradiogroup",
            Self::PointerButton => "pointerbutton",
            Self::Preserve => "preserve",
            Self::Private => "private",
            Self::PtrBtn => "ptrbtn",
            Self::Radiogroup => "radiogroup",
            Self::Redirect => "redirect",
            Self::Redirectgroups => "redirectgroups",
            Self::RedirectKey => "redirectkey",
            Self::Repeat => "repeat",
            Self::Repeating => "repeating",
            Self::Repeats => "repeats",
            Self::Replace => "replace",
            Self::Report => "report",
            Self::Row => "row",
            Self::Same => "same",
            Self::SameServer => "sameserver",
            Self::Screen => "screen",
            Self::Section => "section",
            Self::SetControls => "setcontrols",
            Self::SetGroup => "setgroup",
            Self::SetMods => "setmods",
            Self::SetPointerDefault => "setpointerdefault",
            Self::SetPtrDflt => "setptrdflt",
            Self::Shape => "shape",
            Self::Shift => "shift",
            Self::Solid => "solid",
            Self::SwitchScreen => "switchscreen",
            Self::Symbols => "symbols",
            Self::Terminate => "terminate",
            Self::TerminateServer => "terminateserver",
            Self::Text => "text",
            Self::True => "true",
            Self::Type => "type",
            Self::Unlock => "unlock",
            Self::Usemodmap => "usemodmap",
            Self::Usemodmapmods => "usemodmapmods",
            Self::Value => "value",
            Self::Virtual => "virtual",
            Self::Virtualmod => "virtualmod",
            Self::Virtualmodifier => "virtualmodifier",
            Self::VirtualModifiers => "virtual_modifiers",
            Self::Virtualmodifiers => "virtualmodifiers",
            Self::Virtualmods => "virtualmods",
            Self::Vmods => "vmods",
            Self::Voidsymbol => "voidsymbol",
            Self::Whichgroupstate => "whichgroupstate",
            Self::Whichmodifierstate => "whichmodifierstate",
            Self::Whichmodstate => "whichmodstate",
            Self::Wrapgroups => "wrapgroups",
            Self::X => "x",
            Self::XkbCompat => "xkb_compat",
            Self::XkbCompatibility => "xkb_compatibility",
            Self::XkbCompatibilityMap => "xkb_compatibility_map",
            Self::XkbCompatMap => "xkb_compat_map",
            Self::XkbGeometry => "xkb_geometry",
            Self::XkbKeycodes => "xkb_keycodes",
            Self::XkbKeymap => "xkb_keymap",
            Self::XkbLayout => "xkb_layout",
            Self::XkbSemantics => "xkb_semantics",
            Self::XkbSymbols => "xkb_symbols",
            Self::XkbTypes => "xkb_types",
            Self::Y => "y",
            Self::Yes => "yes",
        }
    }
}

pub(super) static LOWERCASE_TO_MEANING: IndexMap<[u8], Meaning> = IndexMap {
    key: 12913932095322966823,
    disps: &[
        (0, 1),
        (0, 20),
        (0, 7),
        (0, 11),
        (0, 68),
        (0, 1),
        (0, 3),
        (0, 21),
        (0, 2),
        (0, 36),
        (0, 3),
        (0, 26),
        (0, 12),
        (1, 0),
        (0, 31),
        (1, 107),
        (0, 0),
        (0, 1),
        (0, 12),
        (0, 0),
        (0, 5),
        (0, 0),
        (0, 0),
        (1, 6),
        (0, 25),
        (0, 11),
        (0, 0),
        (0, 1),
        (0, 5),
        (0, 10),
        (0, 19),
        (0, 8),
        (0, 143),
        (0, 2),
        (0, 25),
        (0, 7),
        (0, 43),
        (0, 1),
        (0, 3),
        (0, 46),
        (0, 23),
        (0, 66),
        (0, 2),
        (0, 1),
        (0, 60),
        (0, 11),
        (0, 2),
        (0, 6),
        (0, 37),
        (0, 27),
        (0, 0),
        (0, 135),
        (0, 53),
        (0, 76),
        (0, 20),
        (0, 0),
        (0, 132),
        (0, 0),
        (0, 22),
        (0, 66),
        (0, 52),
        (1, 77),
        (0, 8),
        (2, 74),
    ],
    map: &[
        Meaning::Action,
        Meaning::Yes,
        Meaning::Voidsymbol,
        Meaning::Solid,
        Meaning::Overlay,
        Meaning::LockDeviceBtn,
        Meaning::XkbLayout,
        Meaning::Increment,
        Meaning::False,
        Meaning::Same,
        Meaning::Groups,
        Meaning::LatchGroup,
        Meaning::Usemodmap,
        Meaning::On,
        Meaning::No,
        Meaning::Override,
        Meaning::Value,
        Meaning::Vmods,
        Meaning::Whichmodifierstate,
        Meaning::DeviceVal,
        Meaning::Radiogroup,
        Meaning::XkbSymbols,
        Meaning::SetControls,
        Meaning::DeviceValuator,
        Meaning::Indicator,
        Meaning::Locks,
        Meaning::Virtualmod,
        Meaning::Alternate,
        Meaning::Symbols,
        Meaning::Index,
        Meaning::GenerateKeyEvent,
        Meaning::XkbKeycodes,
        Meaning::Mod3,
        Meaning::DeviceButton,
        Meaning::LockPointerBtn,
        Meaning::XkbCompatMap,
        Meaning::Augment,
        Meaning::Redirectgroups,
        Meaning::LockPointerButton,
        Meaning::Data,
        Meaning::XkbCompatibilityMap,
        Meaning::Repeat,
        Meaning::Device,
        Meaning::MessageAction,
        Meaning::Name,
        Meaning::Row,
        Meaning::Both,
        Meaning::ModMap,
        Meaning::AlphanumericKeys,
        Meaning::Virtualmodifier,
        Meaning::LockControls,
        Meaning::Type,
        Meaning::Driveskbd,
        Meaning::MovePtr,
        Meaning::Control,
        Meaning::Groupswrap,
        Meaning::Affect,
        Meaning::LatchToLock,
        Meaning::XkbTypes,
        Meaning::Y,
        Meaning::Clearmodifiers,
        Meaning::Groupsredirect,
        Meaning::Lock,
        Meaning::SetPointerDefault,
        Meaning::NoAction,
        Meaning::Accel,
        Meaning::DevButton,
        Meaning::Keycode,
        Meaning::Button,
        Meaning::XkbGeometry,
        Meaning::All,
        Meaning::Virtualmods,
        Meaning::Whichgroupstate,
        Meaning::Controls,
        Meaning::AlternateGroup,
        Meaning::Locking,
        Meaning::Ctrls,
        Meaning::DevBtn,
        Meaning::RedirectKey,
        Meaning::Unlock,
        Meaning::VirtualModifiers,
        Meaning::Message,
        Meaning::LockDeviceButton,
        Meaning::Shift,
        Meaning::Off,
        Meaning::ClearLocks,
        Meaning::Mod4,
        Meaning::ActionMessage,
        Meaning::Repeats,
        Meaning::LevelName,
        Meaning::Groupname,
        Meaning::Screen,
        Meaning::Driveskeyboard,
        Meaning::True,
        Meaning::Allownone,
        Meaning::Map,
        Meaning::LockPtrBtn,
        Meaning::LockPtrButton,
        Meaning::LockMods,
        Meaning::Report,
        Meaning::SameServer,
        Meaning::Section,
        Meaning::FunctionKeys,
        Meaning::Outline,
        Meaning::Clampgroups,
        Meaning::MovePointer,
        Meaning::KeypadKeys,
        Meaning::Kc,
        Meaning::Accelerate,
        Meaning::Replace,
        Meaning::ISOLock,
        Meaning::Count,
        Meaning::Modmap,
        Meaning::Mod1,
        Meaning::ModifierKeys,
        Meaning::Groupsclamp,
        Meaning::Dfltbtn,
        Meaning::Indicatordriveskbd,
        Meaning::LockDevBtn,
        Meaning::None,
        Meaning::Dev,
        Meaning::Mods,
        Meaning::Redirect,
        Meaning::SetPtrDflt,
        Meaning::TerminateServer,
        Meaning::Neither,
        Meaning::GenKeyEvent,
        Meaning::Defaultbutton,
        Meaning::Shape,
        Meaning::PtrBtn,
        Meaning::Usemodmapmods,
        Meaning::Modifiers,
        Meaning::ModifierMap,
        Meaning::Terminate,
        Meaning::Keys,
        Meaning::SetMods,
        Meaning::Alias,
        Meaning::Allowexplicit,
        Meaning::LatchMods,
        Meaning::Leddriveskbd,
        Meaning::Include,
        Meaning::DeviceBtn,
        Meaning::Virtualmodifiers,
        Meaning::Mod2,
        Meaning::LockGroup,
        Meaning::XkbCompat,
        Meaning::Hidden,
        Meaning::Partial,
        Meaning::Key,
        Meaning::SetGroup,
        Meaning::XkbKeymap,
        Meaning::X,
        Meaning::Nosymbol,
        Meaning::Mod5,
        Meaning::Maximum,
        Meaning::Clearmods,
        Meaning::Indicatordriveskeyboard,
        Meaning::Repeating,
        Meaning::Group,
        Meaning::DevVal,
        Meaning::Whichmodstate,
        Meaning::PointerButton,
        Meaning::LockDevButton,
        Meaning::XkbCompatibility,
        Meaning::Modmapmods,
        Meaning::XkbSemantics,
        Meaning::Actions,
        Meaning::Any,
        Meaning::Logo,
        Meaning::SwitchScreen,
        Meaning::Private,
        Meaning::Interpret,
        Meaning::Preserve,
        Meaning::DevValuator,
        Meaning::Virtual,
        Meaning::Default,
        Meaning::Wrapgroups,
        Meaning::Permanentradiogroup,
        Meaning::Leddriveskeyboard,
        Meaning::Text,
    ],
    _phantom: core::marker::PhantomData,
};

pub(super) static STRING_TO_MEANING: IndexMap<[u8], Meaning> = IndexMap {
    key: 12913932095322966823,
    disps: &[
        (0, 4),
        (0, 0),
        (0, 2),
        (0, 13),
        (0, 18),
        (0, 40),
        (0, 4),
        (0, 53),
        (0, 1),
        (0, 1),
        (0, 2),
        (0, 0),
        (0, 56),
        (1, 0),
        (0, 34),
        (0, 45),
        (0, 0),
        (0, 4),
        (0, 52),
        (0, 0),
        (0, 10),
        (0, 0),
        (0, 76),
        (1, 1),
        (0, 8),
        (0, 88),
        (0, 0),
        (0, 3),
        (0, 31),
        (0, 8),
        (0, 5),
        (0, 2),
        (0, 2),
        (0, 1),
        (0, 27),
        (0, 11),
        (0, 0),
        (0, 5),
        (0, 0),
        (0, 102),
        (0, 19),
        (0, 29),
        (0, 2),
        (1, 41),
        (0, 3),
        (0, 0),
        (3, 89),
        (0, 1),
        (0, 31),
        (0, 11),
        (0, 0),
        (0, 67),
        (2, 123),
        (0, 5),
        (0, 6),
        (0, 16),
        (8, 61),
        (0, 1),
        (0, 21),
        (1, 35),
        (0, 5),
        (0, 4),
        (0, 3),
        (0, 172),
    ],
    map: &[
        Meaning::Overlay,
        Meaning::Increment,
        Meaning::Redirect,
        Meaning::ActionMessage,
        Meaning::Yes,
        Meaning::LockDevButton,
        Meaning::Voidsymbol,
        Meaning::MovePointer,
        Meaning::LockDeviceBtn,
        Meaning::Driveskbd,
        Meaning::DeviceValuator,
        Meaning::Groups,
        Meaning::Usemodmap,
        Meaning::Lock,
        Meaning::No,
        Meaning::Mod2,
        Meaning::Value,
        Meaning::DeviceButton,
        Meaning::Whichmodifierstate,
        Meaning::Indicator,
        Meaning::Vmods,
        Meaning::SwitchScreen,
        Meaning::Unlock,
        Meaning::Symbols,
        Meaning::Virtualmod,
        Meaning::Locks,
        Meaning::XkbSymbols,
        Meaning::Mod5,
        Meaning::LatchMods,
        Meaning::TerminateServer,
        Meaning::Interpret,
        Meaning::Override,
        Meaning::LevelName,
        Meaning::XkbKeycodes,
        Meaning::Off,
        Meaning::ISOLock,
        Meaning::Augment,
        Meaning::Accelerate,
        Meaning::Name,
        Meaning::Data,
        Meaning::XkbCompatibilityMap,
        Meaning::Modmapmods,
        Meaning::Solid,
        Meaning::Alternate,
        Meaning::Repeat,
        Meaning::SetPointerDefault,
        Meaning::Both,
        Meaning::Groupsredirect,
        Meaning::DevVal,
        Meaning::ModMap,
        Meaning::DevValuator,
        Meaning::Message,
        Meaning::On,
        Meaning::LockMods,
        Meaning::MessageAction,
        Meaning::Groupswrap,
        Meaning::Affect,
        Meaning::Button,
        Meaning::XkbTypes,
        Meaning::SetPtrDflt,
        Meaning::SameServer,
        Meaning::LockPtrButton,
        Meaning::Ctrls,
        Meaning::GenerateKeyEvent,
        Meaning::VirtualModifiers,
        Meaning::Accel,
        Meaning::Keycode,
        Meaning::Shift,
        Meaning::XkbGeometry,
        Meaning::AlternateGroup,
        Meaning::LockPtrBtn,
        Meaning::Whichgroupstate,
        Meaning::Controls,
        Meaning::Index,
        Meaning::Locking,
        Meaning::Private,
        Meaning::LatchToLock,
        Meaning::Screen,
        Meaning::RedirectKey,
        Meaning::Partial,
        Meaning::AlphanumericKeys,
        Meaning::ClearLocks,
        Meaning::LockDevBtn,
        Meaning::Mod3,
        Meaning::LockControls,
        Meaning::Mod4,
        Meaning::All,
        Meaning::Usemodmapmods,
        Meaning::LockDeviceButton,
        Meaning::Virtualmodifier,
        Meaning::Section,
        Meaning::Y,
        Meaning::Repeats,
        Meaning::Groupname,
        Meaning::True,
        Meaning::Map,
        Meaning::Driveskeyboard,
        Meaning::Radiogroup,
        Meaning::Report,
        Meaning::LockGroup,
        Meaning::KeypadKeys,
        Meaning::Groupsclamp,
        Meaning::FunctionKeys,
        Meaning::Outline,
        Meaning::Clampgroups,
        Meaning::XkbCompatMap,
        Meaning::LockPointerBtn,
        Meaning::Virtualmodifiers,
        Meaning::Kc,
        Meaning::Neither,
        Meaning::DevBtn,
        Meaning::Virtualmods,
        Meaning::Action,
        Meaning::Modmap,
        Meaning::ModifierKeys,
        Meaning::Control,
        Meaning::Clearmodifiers,
        Meaning::None,
        Meaning::Dfltbtn,
        Meaning::Device,
        Meaning::Dev,
        Meaning::Terminate,
        Meaning::MovePtr,
        Meaning::GenKeyEvent,
        Meaning::Count,
        Meaning::Mods,
        Meaning::Modifiers,
        Meaning::DeviceVal,
        Meaning::Shape,
        Meaning::PtrBtn,
        Meaning::NoAction,
        Meaning::Keys,
        Meaning::Defaultbutton,
        Meaning::SetControls,
        Meaning::ModifierMap,
        Meaning::Allownone,
        Meaning::Leddriveskbd,
        Meaning::Alias,
        Meaning::Text,
        Meaning::Allowexplicit,
        Meaning::Include,
        Meaning::SetGroup,
        Meaning::Same,
        Meaning::Key,
        Meaning::Leddriveskeyboard,
        Meaning::XkbCompat,
        Meaning::Redirectgroups,
        Meaning::False,
        Meaning::Mod1,
        Meaning::Hidden,
        Meaning::XkbKeymap,
        Meaning::X,
        Meaning::Nosymbol,
        Meaning::Maximum,
        Meaning::LockPointerButton,
        Meaning::Clearmods,
        Meaning::Indicatordriveskeyboard,
        Meaning::Group,
        Meaning::XkbCompatibility,
        Meaning::DeviceBtn,
        Meaning::Type,
        Meaning::Actions,
        Meaning::Repeating,
        Meaning::Whichmodstate,
        Meaning::PointerButton,
        Meaning::Replace,
        Meaning::Any,
        Meaning::Preserve,
        Meaning::XkbSemantics,
        Meaning::Logo,
        Meaning::Default,
        Meaning::Wrapgroups,
        Meaning::XkbLayout,
        Meaning::LatchGroup,
        Meaning::Virtual,
        Meaning::Indicatordriveskbd,
        Meaning::Permanentradiogroup,
        Meaning::SetMods,
        Meaning::Row,
        Meaning::DevButton,
    ],
    _phantom: core::marker::PhantomData,
};
