rules = "evdev"
model = "my_model"

[[groups]]
layout = "x1"
variant = ""

[[groups]]
layout = "x2"
variant = ""

[[groups]]
layout = "x3"
variant = ""

[[groups]]
layout = "x4"
variant = ""

[[groups]]
layout = "x5"
variant = ""
