rules = "all_qualifier"
model = "my_model"
options = []

[[groups]]
layout = "layout_x"
variant = ""

[[groups]]
layout = "layout_a"
variant = ""

[[groups]]
layout = "layout_b"
variant = ""

[[groups]]
layout = "layout_c"
variant = ""

[[groups]]
layout = "layout_d"
variant = ""
