rules = "all_qualifier"
model = "my_model"
options = ["my_option"]

[[groups]]
layout = "layout_a"
variant = ""

[[groups]]
layout = "layout_b"
variant = ""

[[groups]]
layout = "layout_a"
variant = ""

[[groups]]
layout = "layout_b"
variant = ""

[[groups]]
layout = "layout_c"
variant = ""
