name: unit-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  latest-glibc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch xkbcommon
        run: git submodule update --init
      - name: Install meson
        run: sudo apt-get install -y meson
      - name: Build xkbcommon
        run: |
          cd libxkbcommon
          meson build -Ddefault_library=static
          cd build
          ninja
      - name: Test
        run: cargo test --all-features --verbose
